# Generated by Django 4.0.3 on 2022-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_appointment_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vip_status',
            field=models.CharField(default='', max_length=10),
        ),
    ]
