# Generated by Django 4.0.3 on 2022-12-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_vin'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='INCOMPLETE', max_length=100),
        ),
    ]
